### ISSUE TITLE
Changes for GCP Otel Collector Configuration

### ISSUE THREAD

**Issue by natefikru** [openrelayxyz/din-caddy-plugins#98]
**Changes for GCP Otel Collector Configuration (`/etc/otel-collector.yml` generation):**

To align the GCP OpenTelemetry Collector configuration with the local setup, modify the deployment script's `printf` command that generates `/etc/otel-collector.yml` to incorporate the following:

1.  **Add the `resource` Processor Definition:**
    *   Under the `processors:` section, add:
        ```yaml
        processors:
          # ... other processors like batch, memory_limiter ...
          resource:
            attributes:
              - action: insert
                key: service.name
                value: "din-caddy" # Adjust value if needed for prod environment
        ```

2.  **Enhance the `filelog` Receiver:**
    *   Modify the existing `filelog` receiver under `receivers:`:
        ```yaml
        receivers:
          # ... other receivers like prometheus, otlp ...
          filelog:
            include: [/srv/caddy.log]
            start_at: beginning
            operators:
              - type: json_parser
                # Add this line to parse log fields into attributes
                parse_to: attributes
                id: caddy_log_parser
            # Add this block to attach job/container labels
            attributes:
              job: din-caddy      # Or a relevant job name for prod
              container: din-caddy  # Or a relevant container name for prod
        ```

3.  **Include `resource` Processor in Pipelines:**
    *   Update the `pipelines:` section under `service:`:
        ```yaml
        service:
          pipelines:
            metrics:
              receivers: [prometheus, otlp] # Ensure necessary receivers are present
              # Add 'resource' to the processors list
              processors: [batch, resource] # Add other necessary processors
              exporters: [otlp] # Keep only necessary exporters for prod
            logs:
              receivers: [filelog, otlp]  # Ensure necessary receivers are present
              # Add 'resource' to the processors list
              processors: [resource, memory_limiter, batch] # Add other necessary processors
              exporters: [otlp, logging] # Keep only necessary exporters for prod (logging optional)
          # ... rest of service section (telemetry, etc.)
        ```

**Summary:**

Modify the GCP deployment script to generate an `/etc/otel-collector.yml` that includes:
*   The `resource:` processor block.
*   The updated `filelog:` receiver block (`parse_to: attributes` and the `attributes:` map).
*   The `resource` identifier added to the `processors:` list within *both* the `metrics:` and `logs:` pipelines.
